#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Ensure Caddy config directories have appropriate permissions
mkdir -p /data/caddy /config/caddy
chown -R $WWWUSER:sail /data /config

if [ ! -d /.composer ]; then
    mkdir -p /.composer
fi

chmod -R ugo+rw /.composer

export SUPERVISOR_PHP_USER="sail"
export SUPERVISOR_PHP_COMMAND="/usr/local/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=80 --admin-port=2019"
export SUPERVISOR_VITE_USER="sail"

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
fi
